vault view
valorem-labs-inc/valorem-frontend pull request #74
Opened 2022-07-11 12:25 UTC by thal0x

- [X] Implement Vault view
- [x] Mobile Friendly
- [x] Tests

Closes #2

2022-07-14 18:02 UTC, 0xAlcibiades requested changes

2022-07-15 14:09 UTC, thal0x commented on components/blankState/index.css.ts
> +  background-color: var(--gray-200);
This isn't in the new design, I thought all white looked a little odd but I can change it back if that's what you want

2022-07-15 14:20 UTC, thal0x commented on components/networkButton/NetworkButton.tsx
> +            d="M12.5789 1.72305L7.3535 6.72969C7.1785 6.87734 7.01443 6.9375 6.87498 6.9375C6.73553 6.9375 6.54768 6.87682 6.42135 6.75463L1.17135 1.72305C0.908958 1.47422 0.900427 1.03398 1.15166 0.
Do you want the same for the wallet button as well?

2022-07-15 14:29 UTC, thal0x commented on graphql/hooks/useOptions.ts
> +        ({ token }) => token.type === 1
Maybe we can deal with it in another story, since we had talked about reworking the graph anyways?

2022-07-15 14:37 UTC, thal0x commented on components/mobileMenu/elements.ts
> +  width: 420px;
Fixed.

2022-07-15 14:38 UTC, thal0x commented on components/networkButton/NetworkButton.tsx
> +            d="M12.5789 1.72305L7.3535 6.72969C7.1785 6.87734 7.01443 6.9375 6.87498 6.9375C6.73553 6.9375 6.54768 6.87682 6.42135 6.75463L1.17135 1.72305C0.908958 1.47422 0.900427 1.03398 1.15166 0.
Done, and also added the link to the wallet button

2022-07-15 14:38 UTC, thal0x commented on lib/hooks/useEventListener.ts
> +import { RefObject, useEffect, useRef } from "react";
Done.

2022-07-15 14:38 UTC, thal0x commented on lib/hooks/useMediaQuery.ts
> +import { useState, useEffect } from "react";
Done.

2022-07-15 21:36 UTC, 0xAlcibiades approved these changes

2022-07-15 21:36 UTC, merged